//Styles
import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { AlyveCalorieTrackProvider } from "@/context/provider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Calories Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AlyveCalorieTrackProvider>{children}</AlyveCalorieTrackProvider>
      </body>
    </html>
  );
}
