import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FoodLog",
  description: "Generated by create next app",
};

export default function FoodLogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
